version: "3"
services:
  db:
    container_name: db-mysql
    image: mysql:5.6
    networks:
      - spring
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
  api:
    container_name: api
    image: openjdk:11
    restart: on-failure
    networks:
      - spring
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint:
      [
        "/app/mvnw",
        "spring-boot:run",
        "-Dspring-boot.run.profiles=mysql",
        "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000'",
      ]
networks:
  spring:
    driver: bridge
